{{- if and (eq (include "mistral.k8sSaAuthEnabled" .) "true") (not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "mistral-token-reviewer")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mistral-token-reviewer
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
{{- end }}
